//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutputParser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OutputParser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #BESTPOS,Property
        ///2,Latitude (Degrees)
        ///3,Longitude (Degrees)
        ///4,Height (Meters Above Sea Level)
        ///5,Undulation (Geoid-Ellipsoid Relation)
        ///6,Datum ID Number
        ///7,Latitude Standard Deviation (Meters)
        ///8,Longitude Standard Deviation (Meters)
        ///9,Height Standard Deviation (Meters)
        ///10,Base Station ID
        ///11,Differential Age (Seconds)
        ///12,Solution Age (Seconds)
        ///13,Satellites Tracked
        ///14,Satellites in Solution
        ///15,Satellites in Solution (With L1/E1/B1)
        ///16,Satellites in Solution (With Multi-Frequency)
        ///.
        /// </summary>
        internal static string BESTPOS0 {
            get {
                return ResourceManager.GetString("BESTPOS0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #BESTPOS-Solution Status,Value,Message
        ///0,SOL_COMPUTED,Solution Computed
        ///1,INSUFFICIENT_OBS,Insufficient Observations
        ///2,NO_CONVERGENCE,No Convergence
        ///3,SINGULARITY,Singularity at Parameter Matrix
        ///4,COV_TRACE,Covariance Trace Exceeds 1000 Meters
        ///5,TEST_DIST,Test Distance Exceeded
        ///6,COLD_START,Not Yet Converged from Cold Start
        ///7,V_H_LIMIT,Height or Velocity Limit Exceeded
        ///8,VARIANCE,Variance Limit Exceeded
        ///9,RESIDUALS,Residual Limit Exceeded
        ///13,INTEGRITY_WARNING,Large Residuals: Position Unreliable        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BESTPOS1 {
            get {
                return ResourceManager.GetString("BESTPOS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #BESTPOS-Solution Status,Value,Message
        ///0,NONE,No Solution
        ///1,FIXEDPOS,Position Fixed (FIX POSITION)
        ///2,FIXEDHEIGHT,Position Fixed (FIX HEIGHT/AUTO)
        ///8,DOPPLER_VELOCITY,Velocity Computed (Doppler)
        ///16,SINGLE,Single Point Position
        ///17,PSRDIFF,Pseudorange Differential Solution
        ///18,WAAS,Solution Calculated (WAAS)
        ///19,PROPAGATED,Propagated (Kalman Filter)
        ///20,OMNISTAR,OmniSTAR VBS Position
        ///32,L1_FLOAT,Floating L1 Ambiguity Solution
        ///33,IONOFREE_FLOAT,Floating Ionospheric-Free Ambiguity Solution
        ///34,NARROW_FLOA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BESTPOS2 {
            get {
                return ResourceManager.GetString("BESTPOS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #HDR_STAT-Receiver Status,Property,0,1
        ///1,Temperature,Within Specifications,Warning
        ///2,Voltage Supply,OK,Warning
        ///3,Antenna Power,Powered,Not Powered
        ///4,Low-Noise Amplifier,OK,Failure
        ///5,Antenna Open,OK,Open
        ///6,Antenna Shorted,OK,Shorted
        ///7,CPU Overload,No Overload,Overload
        ///8,COM1 Buffer Overrun,No Overrun,Overrun
        ///9,COM2 Buffer Overrun,No Overrun,Overrun
        ///10,COM3 Buffer Overrun,No Overrun,Overrun
        ///11,Link Overrun,No Overrun,Overrun
        ///13,Auxiliary Transmit Overrun,No Overrun,Overrun
        ///14,Automatic Gain Contr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HDR_STAT {
            get {
                return ResourceManager.GetString("HDR_STAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #HDR_STAT-GPS Time Status,Value,Message
        ///20,UNKNOWN,Unknown
        ///60,APPROXIMATE,Approximate
        ///80,COARSEADJUSTING,Approaching Coarse Precision
        ///100,COARSE,Coarse Precision
        ///120,COARSESTEERING,Coarse Precision (Steering)
        ///130,FREEWHEELING,Position Lost
        ///140,FINEADJUSTING,Approaching Fine Precision
        ///160,FINE,Fine Precision
        ///170,FINEBACKUPSTEERING,Fine Precision (Backup Steering)
        ///180,FINESTEERING,Fine Precision (Steering)
        ///200,SATTIME,Satellite Time
        ///.
        /// </summary>
        internal static string HDR_TIME {
            get {
                return ResourceManager.GetString("HDR_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #RXSTATUS-Receiver Error,Property,0,1
        ///0,Error: DRAM,OK,Error
        ///1,Error: Invalid Firmware,OK,Error
        ///2,Error: ROM,OK,Error
        ///4,Error: Electronic Serial Number Inaccessible,OK,Error
        ///5,Error: Authorization Code,OK,Error
        ///6,Error: Slow ADC Not Initialized,OK,Error
        ///7,Error: Supply Voltage,OK,Error
        ///8,Error: Thermometer Not Read,OK,Error
        ///9,Error: Temperature,OK,Error
        ///10,Error: MINOS,OK,Error
        ///11,Error: PLL RF1 Hardware,OK,Error
        ///12,Error: PLL RF2 Hardware,OK,Error
        ///13,Error: PLL RF3 Hardware,OK,Error
        ///14,Error: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RXSTATU0 {
            get {
                return ResourceManager.GetString("RXSTATU0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #RXSTATUS-Auxiliary 1,Property,0,1
        ///3,Position Averaging,Off,On
        ///7,USB Connection Status,Connected,Not Connected
        ///8,USB1 Buffer Overrun,No Overrun,Overrun
        ///9,USB2 Buffer Overrun,No Overrun,Overrun
        ///10,USB3 Buffer Overrun,No Overrun,Overrun
        ///12,Error: Profile Activation,OK,Error
        ///14,RF1 Automatic Gain Control Status,OK,Out of Range
        ///15,RF2 Automatic Gain Control Status,OK,Out of Range
        ///16,RF3 Automatic Gain Control Status,OK,Out of Range
        ///17,RF4 Automatic Gain Control Status,OK,Out of Range
        ///18,Ethernet Stat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RXSTATU1 {
            get {
                return ResourceManager.GetString("RXSTATU1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #RXSTATUS-Auxiliary 2,Property,0,1
        ///0,Error: SPI Communication Failure,OK,Error
        ///1,Error: I-Squared C Communication Failure,OK,Error
        ///2,COM4 Buffer Overrun,No Overrun,Overrun
        ///3,COM5 Buffer Overrun,No Overrun,Overrun
        ///4,COM6 Buffer Overrun,No Overrun,Overrun
        ///5,COM7 Buffer Overrun,No Overrun,Overrun
        ///6,COM8 Buffer Overrun,No Overrun,Overrun
        ///7,COM9 Buffer Overrun,No Overrun,Overrun
        ///8,COM10 Buffer Overrun,No Overrun,Overrun
        ///.
        /// </summary>
        internal static string RXSTATU2 {
            get {
                return ResourceManager.GetString("RXSTATU2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #RXSTATUS-Auxiliary 3,Property,0,1
        ///1,WCOM1 Buffer Overrun,No Overrun,Overrun
        ///2,FILE Buffer Overrun,No Overrun,Overrun
        ///3,Bluetooth Buffer Overrun,No Overrun,Overrun
        ///8,Wi-Fi Power,Not Powered,Overrun
        ///9,Wi-Fi Mode,Client Mode,AP Mode
        ///10,Wi-Fi Conection,Not Established,Established
        ///10,Wi-Fi Connection (If AP Mode),Not Ready,Ready
        ///10,Wi-Fi Connection (If Client Mode),Not Connected to AP,Connected to AP
        ///11,Bluetooth Power,Not Powered,Powered
        ///12,Bluetooth SPP Pairing,Not Connected,Connected
        ///13,Cell Radio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RXSTATU3 {
            get {
                return ResourceManager.GetString("RXSTATU3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #TIME,Property
        ///4,UTC Year
        ///5,UTC Month
        ///6,UTC Day
        ///7,UTC Hour
        ///8,UTC Minute
        ///9,UTC Millisecond
        ///.
        /// </summary>
        internal static string TIME0 {
            get {
                return ResourceManager.GetString("TIME0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #TIME-Clock Model Status,Value,Message
        ///0,VALID,Valid
        ///1,CONVERGING,Almost Valid (Converging)
        ///2,ITERATING,Almost Valid (Iterating)
        ///3,INVALID,Invalid
        ///4,ERROR,Error
        ///.
        /// </summary>
        internal static string TIME1 {
            get {
                return ResourceManager.GetString("TIME1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #TIME-UTC Status,Value,Message
        ///0,0,Invalid
        ///1,1,Valid
        ///2,2,Warning
        ///.
        /// </summary>
        internal static string TIME2 {
            get {
                return ResourceManager.GetString("TIME2", resourceCulture);
            }
        }
    }
}
